name: Run Gradle on PRs
on: push
jobs:
    gradle:
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-java@v3
              with:
                  distribution: temurin
                  java-version: 17

            - name: Backend 'build' task
              uses: gradle/gradle-build-action@v2
              with:
                  arguments: :backend:build
                  build-root-directory: composite